export const cardData = [
    {
        id: 1,
        location: "Mahakal",
        title: "Mahakaleshwar Temple",
        description: "One of the 12 Jyotirlingas, the Mahakaleshwar temple is dedicated to Lord Shiva and holds immense religious significance.",
        image: ma1,
        alt: "Mahakaleshwar Temple exterior at dusk",
        link: "/temple",
        date: "May 5, 2025",
        readTime: "4 min read",
        views: "2.4k",
        category: "Temple",
        featured: true
    },
    {
        id: 2,
        location: "Mahakal",
        title: "Bhasma Aarti",
        description: "Experience the divine Bhasma Aarti, a unique ritual performed during the early hours of the morning.",
        image: ma2,
        alt: "Bhasma Aarti ritual",
        link: "/bhasma-aarti",
        date: "May 2, 2025",
        readTime: "3 min read",
        views: "3.1k",
        category: "Rituals",
        new: true
    },
    {
        id: 3,
        location: "Mahakal",
        title: "Mahakaleshwar Weather",
        description: "Plan your visit to Mahakaleshwar with our comprehensive weather guide for all seasons.",
        image: ma3,
        alt: "Mahakaleshwar Temple view with clouds",
        link: "/weather",
        date: "April 28, 2025",
        readTime: "2 min read",
        views: "1.6k",
        category: "Travel"
    },
    {
        id: 4,
        location: "Mahakal",
        title: "Festivals at Mahakaleshwar",
        description: "Discover the vibrant festivals celebrated at Mahakaleshwar throughout the year.",
        image: ma4,
        alt: "Festival celebrations at Mahakaleshwar",
        link: "/festivals",
        date: "April 20, 2025",
        readTime: "5 min read",
        views: "1.9k",
        category: "Festivals"
    },
    {
        id: 5,
        location: "Mahakal",
        title: "Temple History",
        description: "Explore the rich history and legends associated with the ancient Mahakaleshwar Temple.",
        image: ma5,
        alt: "History of Mahakaleshwar",
        link: "/history",
        date: "April 15, 2025",
        readTime: "6 min read",
        views: "2.7k",
        category: "History",
        featured: true
    },
    {
        id: 6,
        location: "Mahakal",
        title: "Temple Architecture",
        description: "Marvel at the magnificent architecture and spiritual design of the Mahakaleshwar Temple.",
        image: ma6,
        alt: "Architecture view of Mahakaleshwar",
        link: "/architecture",
        date: "April 10, 2025",
        readTime: "4 min read",
        views: "2.1k",
        category: "Architecture"
    },
    {
        id: 7,
        location: "Mahakal",
        title: "How to Reach",
        description: "Find the best routes and transportation options to reach Mahakaleshwar Temple from major cities.",
        image: ma7,
        alt: "Transportation to Mahakaleshwar",
        link: "/directions",
        date: "April 5, 2025",
        readTime: "3 min read",
        views: "1.3k",
        category: "Travel"
    },
    {
        id: 8,
        location: "Mahakal",
        title: "Accommodation Guide",
        description: "Browse through our curated list of hotels and dharamshalas near Mahakaleshwar Temple.",
        image: ma8,
        alt: "Accommodations near Mahakaleshwar Temple",
        link: "/stay",
        date: "April 2, 2025",
        readTime: "3 min read",
        views: "1.5k",
        category: "Stay"
    },
    {
        id: 9,
        location: "Mahakal",
        title: "Nearby Attractions",
        description: "Explore other places of interest near Mahakaleshwar Temple during your visit to Ujjain.",
        image: ma9,
        alt: "Nearby Attractions",
        link: "/attractions",
        date: "March 30, 2025",
        readTime: "6 min read",
        views: "2.2k",
        category: "Attractions"
    }
];
